name: family_expense_tracker
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  core:
    path: core

  equatable: ^2.0.2
  flutter_bloc: ^8.0.0
  get_it: ^7.1.3
  provider: ^6.0.3
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2
  firebase_auth_web: ^5.1.2
  google_fonts: ^5.1.0
  bloc: ^8.1.4
  intl: any
  shared_preferences: ^2.2.3
  injectable: ^2.4.4
  flutter_colorpicker: ^1.1.0
  shimmer: ^3.0.0
  firebase_messaging: ^15.0.4
  http: ^1.2.2
  fl_chart: ^0.68.0
  flutter_svg: ^2.0.10+1
  dartz: ^0.10.1
  universal_html: ^2.2.4
  flutter_launcher_icons: ^0.13.1
  excel: ^4.0.6
  pwa_install: ^0.0.5
  flutter_phoenix: ^1.1.1
  universal_io: ^2.2.2

  
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  injectable_generator: ^2.1.3
  flutter_lints: ^3.0.0
  bloc_test: ^9.0.0
  mockito: ^5.0.8
  analyzer: ^6.4.1
  intl_utils: ^2.8.7

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/icon/

flutter_intl:
  enabled: true
  nullable: false