name: core
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.2.0
  firebase_crashlytics: ^4.0.3
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.2
  google_fonts: ^5.1.0
  shared_preferences: ^2.2.3
  http: ^1.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: