name: core
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.2
  google_fonts: ^5.1.0
  shared_preferences: ^2.2.3
  http: ^1.2.2
  intl: ^0.19.0
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1
  internet_connection_checker: ^1.0.0+1
  get_it: ^7.1.3
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: